version: "3.9"
services:

  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_DB: "car_rental_spring_rest"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"